/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Controllers.ItemController;
import Models.Item;
import java.awt.event.ActionListener;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Ricardo
 */
public class ItemView extends javax.swing.JPanel {
    
    private ItemController itemCtrl;
    private TableERP tableERP;
    private Object[][] data;
    private String[] column;

    /**
     * Creates new form ItemView
     */
    public ItemView() {
        initComponents();  
        
        fieldSearchMaHang.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) {
                disableField();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                disableField();
            }
            @Override
            public void insertUpdate(DocumentEvent e) {
                disableField();
            }

            public void disableField() {
                if (fieldSearchMaHang.getText().trim().isEmpty()) {
                    fieldSearchTenHang.setEnabled(true);
                } else {
                    fieldSearchTenHang.setEnabled(false);
                }
            }
        });
        fieldSearchTenHang.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) {
                disableField();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                disableField();
            }
            @Override
            public void insertUpdate(DocumentEvent e) {
                disableField();
            }

            public void disableField() {
                if (fieldSearchTenHang.getText().trim().isEmpty()) {
                    fieldSearchMaHang.setEnabled(true);
                } else {
                    fieldSearchMaHang.setEnabled(false);
                }
            }
        });
        
    }

    public TableERP getTableERP() {
        return tableERP;
    }

    public Object[][] getData() {
        return data;
    }

    public void setData(Object[][] data) {
        this.data = data;
    }

    public String[] getColumn() {
        return column;
    }

    public void setColumn(String[] column) {
        this.column = column;
    }
    
    public JTable getTbUser() {
        return tbItem;
    }

    public JTable getTbItem() {
        return tbItem;
    }
    
    public JDialog getDialogAdd() {
        return DialogAdd;
    }

    public JTextField getFieldMaHang_add() {
        return fieldMaHang_add;
    }

    public JDialog getDialogUpdate() {
        return DialogUpdate;
    }
    
    public JTextField getFieldMaHang_update() {
        return fieldMaHang_update;
    }    

    public void setFieldMaHang_add(JTextField fieldMaHang_add) {
        this.fieldMaHang_add = fieldMaHang_add;
    }
    
    public int getSelRow(){
        return tbItem.getSelectedRow();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogAdd = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        fieldMaHang_add = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fieldTenHang_add = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fieldDVT_add = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        fieldDonGia_add = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnDialogAdd = new javax.swing.JButton();
        DialogUpdate = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        fieldMaHang_update = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        fieldTenHang_update = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        fieldDVT_update = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        fieldDonGia_update = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnDialogUpdate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        fieldSearchTenHang = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fieldSearchMaHang = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbItem = new javax.swing.JTable();
        btnLoad = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        DialogAdd.setModal(true);

        jLabel7.setText("Mã hàng");

        fieldMaHang_add.setEditable(false);

        jLabel8.setText("Tên hàng");

        jLabel9.setText("Đơn vị");

        jLabel10.setText("Đơn giá");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("THÊM MỚI ITEM");

        btnDialogAdd.setText("Thêm");

        javax.swing.GroupLayout DialogAddLayout = new javax.swing.GroupLayout(DialogAdd.getContentPane());
        DialogAdd.getContentPane().setLayout(DialogAddLayout);
        DialogAddLayout.setHorizontalGroup(
            DialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogAddLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(DialogAddLayout.createSequentialGroup()
                .addGroup(DialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DialogAddLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(DialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel10))
                        .addGap(27, 27, 27)
                        .addGroup(DialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldDonGia_add)
                            .addComponent(fieldDVT_add, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldMaHang_add)
                            .addComponent(fieldTenHang_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogAddLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDialogAdd)))
                .addContainerGap())
        );
        DialogAddLayout.setVerticalGroup(
            DialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogAddLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel11)
                .addGap(50, 50, 50)
                .addGroup(DialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fieldMaHang_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(fieldTenHang_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(fieldDVT_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(fieldDonGia_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btnDialogAdd)
                .addContainerGap())
        );

        DialogUpdate.setModal(true);

        jLabel12.setText("Mã hàng");

        fieldMaHang_update.setEditable(false);

        jLabel13.setText("Tên hàng");

        jLabel14.setText("Đơn vị");

        jLabel15.setText("Đơn giá");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setText("CẬP NHẬT ITEM");

        btnDialogUpdate.setText("Cập nhật");

        javax.swing.GroupLayout DialogUpdateLayout = new javax.swing.GroupLayout(DialogUpdate.getContentPane());
        DialogUpdate.getContentPane().setLayout(DialogUpdateLayout);
        DialogUpdateLayout.setHorizontalGroup(
            DialogUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogUpdateLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(DialogUpdateLayout.createSequentialGroup()
                .addGroup(DialogUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DialogUpdateLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(DialogUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DialogUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel15))
                        .addGap(27, 27, 27)
                        .addGroup(DialogUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldDonGia_update)
                            .addComponent(fieldDVT_update, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldMaHang_update)
                            .addComponent(fieldTenHang_update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogUpdateLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDialogUpdate)))
                .addContainerGap())
        );
        DialogUpdateLayout.setVerticalGroup(
            DialogUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogUpdateLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel16)
                .addGap(50, 50, 50)
                .addGroup(DialogUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(fieldMaHang_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DialogUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(fieldTenHang_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DialogUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(fieldDVT_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DialogUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(fieldDonGia_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btnDialogUpdate)
                .addContainerGap())
        );

        setBorder(javax.swing.BorderFactory.createTitledBorder("Quản lý danh mục hàng hoá - dịch vụ"));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm"));

        jLabel1.setText("Mã hàng");

        btnSearch.setText("Tìm kiếm");

        jLabel2.setText("Tên hàng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldSearchMaHang, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldSearchTenHang, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldSearchMaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(jLabel2)
                    .addComponent(fieldSearchTenHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Bảng Item"));

        tbItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã hàng", "Tên hàng", "Đơn vị", "Đơn giá (VND)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbItem.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbItem.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tbItem);

        btnLoad.setText("Load");

        btnDelete.setText("Xoá");

        btnUpdate.setText("Sửa");

        btnAdd.setText("Thêm");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnLoad)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoad)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate)
                    .addComponent(btnAdd)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void btnLoadActionListener(ActionListener listener){
        btnLoad.addActionListener(listener);
    }
    
    public void btnAddActionListener(ActionListener listener){
        btnAdd.addActionListener(listener);
    }
    
    public void btnDialogAddActionListener(ActionListener listener){
        btnDialogAdd.addActionListener(listener);
    }
    
    public Item getFieldDiaglogAdd(){
        String maHangStr = fieldMaHang_add.getText();
        String donGiaStr = fieldDonGia_add.getText();
        String tenHang = fieldTenHang_add.getText();
        String dvt = fieldDVT_add.getText();

        // Kiểm tra các trường nếu để rỗng
        if (donGiaStr.isEmpty() || tenHang.isEmpty() || dvt.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập vào tất cả các trường.");
            return null;
        }

        // Kiểm tra các trường số chỉ chứa số với method .matches("\\d+") {\\d: bất kỳ ký tự số} {+: lặp lại (nhóm) ký tự trước đó}
        if (!donGiaStr.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Giá trị không hợp lệ. Vui lòng nhập số cho trường \"Đơn giá\"");
            return null;
        }

        int maHang = Integer.parseInt(maHangStr);
        long donGia = Long.parseLong(donGiaStr);

        Item item = new Item(maHang, tenHang, dvt, donGia, 0);
        return item;   
    }
    
    public void btnUpdateActionListener(ActionListener listener){
        btnUpdate.addActionListener(listener);
    }
    
    public void btnDialogUpdateActionListener(ActionListener listener){
        btnDialogUpdate.addActionListener(listener);
    }
    
    public Item getFieldDiaglogUpdate(){
        String maHangStr = fieldMaHang_update.getText();
        String donGiaStr = fieldDonGia_update.getText();
        String tenHang = fieldTenHang_update.getText();
        String dvt = fieldDVT_update.getText();

        // Kiểm tra các trường nếu để rỗng
        if (donGiaStr.isEmpty() || tenHang.isEmpty() || dvt.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tất cả các trường không được để trống.");
            return null;
        }

        // Kiểm tra các trường số chỉ chứa số với method .matches("\\d+") {\\d: bất kỳ ký tự số} {+: lặp lại (nhóm) ký tự trước đó}
        if (!donGiaStr.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Giá trị không hợp lệ. Vui lòng nhập số cho trường \"Đơn giá\"");
            return null;
        }

        int maHang = Integer.parseInt(maHangStr);
        long donGia = Long.parseLong(donGiaStr);

        Item item = new Item(maHang, tenHang, dvt, donGia, 0);
        return item;   
    }
    
    public void btnDeleteActionListener(ActionListener listener){
        btnDelete.addActionListener(listener);
    }
    
    public void btnSearchActionListener(ActionListener listener){
        btnSearch.addActionListener(listener);
    }
    
    public String[] getSearchParams(){
        String[] searchParams = new String[2];
        searchParams[0] = fieldSearchMaHang.getText();
        searchParams[1] = fieldSearchTenHang.getText();
        return searchParams;
    } 
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog DialogAdd;
    private javax.swing.JDialog DialogUpdate;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDialogAdd;
    private javax.swing.JButton btnDialogUpdate;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField fieldDVT_add;
    private javax.swing.JTextField fieldDVT_update;
    private javax.swing.JTextField fieldDonGia_add;
    private javax.swing.JTextField fieldDonGia_update;
    private javax.swing.JTextField fieldMaHang_add;
    private javax.swing.JTextField fieldMaHang_update;
    private javax.swing.JTextField fieldSearchMaHang;
    private javax.swing.JTextField fieldSearchTenHang;
    private javax.swing.JTextField fieldTenHang_add;
    private javax.swing.JTextField fieldTenHang_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbItem;
    // End of variables declaration//GEN-END:variables

    public void setController(ItemController itemController) {
        this.itemCtrl = itemController;
    }

    public void loadData() {
        tableERP = new TableERP(data, column);
        tbItem.setModel(tableERP);       
    }

    public void DialogAddClearField() {
        fieldMaHang_add.setText("");
        fieldDonGia_add.setText("");
        fieldTenHang_add.setText("");
        fieldDVT_add.setText("");
    }

    public void setFieldMaHang_update() {
        int selRow = tbItem.getSelectedRow();
        fieldMaHang_update.setText(String.valueOf(tbItem.getValueAt(selRow, 0)));
        fieldTenHang_update.setText((String) tbItem.getValueAt(selRow, 1));
        fieldDVT_update.setText((String) tbItem.getValueAt(selRow, 2));
        fieldDonGia_update.setText(String.valueOf(tbItem.getValueAt(selRow, 3)));
        
    }

    public int selectRow() {
        return tbItem.getSelectedRow();
    }

}
